'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls
Imports RibbonLib.Interop

Partial Class RibbonItems

    ' ContextPopup CommandName

    Private _Ribbon As Ribbon, _ApplicationMenu As RibbonApplicationMenu, _ButtonNew As RibbonButton, _ButtonOpen As RibbonButton, _ButtonSave As RibbonButton, _ButtonExit As RibbonButton

    Private NotInheritable Class Cmd
        Public Const cmdApplicationMenu As UInteger = 1000
        Public Const cmdButtonNew As UInteger = 1001
        Public Const cmdButtonOpen As UInteger = 1002
        Public Const cmdButtonSave As UInteger = 1003
        Public Const cmdButtonExit As UInteger = 1004
    End Class

    Public Property Ribbon As Ribbon
        Get
            Return _Ribbon
        End Get
        Private Set(ByVal value As Ribbon)
            _Ribbon = value
        End Set
    End Property

    Public Property ApplicationMenu As RibbonApplicationMenu
        Get
            Return _ApplicationMenu
        End Get
        Private Set(ByVal value As RibbonApplicationMenu)
            _ApplicationMenu = value
        End Set
    End Property

    Public Property ButtonNew As RibbonButton
        Get
            Return _ButtonNew
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNew = value
        End Set
    End Property

    Public Property ButtonOpen As RibbonButton
        Get
            Return _ButtonOpen
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonOpen = value
        End Set
    End Property

    Public Property ButtonSave As RibbonButton
        Get
            Return _ButtonSave
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSave = value
        End Set
    End Property

    Public Property ButtonExit As RibbonButton
        Get
            Return _ButtonExit
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonExit = value
        End Set
    End Property

    Public Sub New(ByVal ribbon As Ribbon)
        If ribbon Is Nothing Then Throw New ArgumentNullException(NameOf(ribbon), "Parameter is null")
        Me.Ribbon = ribbon
        ApplicationMenu = New RibbonApplicationMenu(ribbon, Cmd.cmdApplicationMenu)
        ButtonNew = New RibbonButton(ribbon, Cmd.cmdButtonNew)
        ButtonOpen = New RibbonButton(ribbon, Cmd.cmdButtonOpen)
        ButtonSave = New RibbonButton(ribbon, Cmd.cmdButtonSave)
        ButtonExit = New RibbonButton(ribbon, Cmd.cmdButtonExit)
    End Sub
End Class
