'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls
Imports RibbonLib.Interop

Partial Class RibbonItems

    ' ContextPopup CommandName

    Private _Ribbon As Ribbon, _Recents As RibbonRecentItems, _ButtonNew As RibbonButton, _ButtonOpen As RibbonButton, _ButtonSave As RibbonButton, _RsharpDev As RibbonDropDownButton, _About As RibbonButton, _Help As RibbonHelpButton, _TabMain As RibbonTab, _GroupCommon As RibbonGroup, _GroupSimple As RibbonGroup, _ButtonSwitchToAdvanced As RibbonButton, _RunScript As RibbonButton, _RunRemote As RibbonButton, _GroupAdvanced As RibbonGroup, _ButtonSwitchToSimple As RibbonButton, _ButtonDropA As RibbonButton, _ButtonDropB As RibbonButton, _ButtonDropC As RibbonButton

    Private NotInheritable Class Cmd
        Public Const cmdRecents As UInteger = 15
        Public Const cmdButtonNew As UInteger = 1005
        Public Const cmdButtonOpen As UInteger = 1006
        Public Const cmdButtonSave As UInteger = 1007
        Public Const cmdRsharpDev As UInteger = 17
        Public Const cmdAbout As UInteger = 16
        Public Const cmdHelp As UInteger = 14
        Public Const cmdTabMain As UInteger = 1001
        Public Const cmdGroupCommon As UInteger = 1002
        Public Const cmdGroupSimple As UInteger = 1003
        Public Const cmdButtonSwitchToAdvanced As UInteger = 1011
        Public Const cmdRunScript As UInteger = 18
        Public Const cmdRunRemote As UInteger = 19
        Public Const cmdGroupAdvanced As UInteger = 1004
        Public Const cmdButtonSwitchToSimple As UInteger = 1012
        Public Const cmdButtonDropA As UInteger = 1008
        Public Const cmdButtonDropB As UInteger = 1009
        Public Const cmdButtonDropC As UInteger = 1010
    End Class

    Public Property Ribbon As Ribbon
        Get
            Return _Ribbon
        End Get
        Private Set(ByVal value As Ribbon)
            _Ribbon = value
        End Set
    End Property

    Public Property Recents As RibbonRecentItems
        Get
            Return _Recents
        End Get
        Private Set(ByVal value As RibbonRecentItems)
            _Recents = value
        End Set
    End Property

    Public Property ButtonNew As RibbonButton
        Get
            Return _ButtonNew
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNew = value
        End Set
    End Property

    Public Property ButtonOpen As RibbonButton
        Get
            Return _ButtonOpen
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonOpen = value
        End Set
    End Property

    Public Property ButtonSave As RibbonButton
        Get
            Return _ButtonSave
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSave = value
        End Set
    End Property

    Public Property RsharpDev As RibbonDropDownButton
        Get
            Return _RsharpDev
        End Get
        Private Set(ByVal value As RibbonDropDownButton)
            _RsharpDev = value
        End Set
    End Property

    Public Property About As RibbonButton
        Get
            Return _About
        End Get
        Private Set(ByVal value As RibbonButton)
            _About = value
        End Set
    End Property

    Public Property Help As RibbonHelpButton
        Get
            Return _Help
        End Get
        Private Set(ByVal value As RibbonHelpButton)
            _Help = value
        End Set
    End Property

    Public Property TabMain As RibbonTab
        Get
            Return _TabMain
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabMain = value
        End Set
    End Property

    Public Property GroupCommon As RibbonGroup
        Get
            Return _GroupCommon
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupCommon = value
        End Set
    End Property

    Public Property GroupSimple As RibbonGroup
        Get
            Return _GroupSimple
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupSimple = value
        End Set
    End Property

    Public Property ButtonSwitchToAdvanced As RibbonButton
        Get
            Return _ButtonSwitchToAdvanced
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSwitchToAdvanced = value
        End Set
    End Property

    Public Property RunScript As RibbonButton
        Get
            Return _RunScript
        End Get
        Private Set(ByVal value As RibbonButton)
            _RunScript = value
        End Set
    End Property

    Public Property RunRemote As RibbonButton
        Get
            Return _RunRemote
        End Get
        Private Set(ByVal value As RibbonButton)
            _RunRemote = value
        End Set
    End Property

    Public Property GroupAdvanced As RibbonGroup
        Get
            Return _GroupAdvanced
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupAdvanced = value
        End Set
    End Property

    Public Property ButtonSwitchToSimple As RibbonButton
        Get
            Return _ButtonSwitchToSimple
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSwitchToSimple = value
        End Set
    End Property

    Public Property ButtonDropA As RibbonButton
        Get
            Return _ButtonDropA
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropA = value
        End Set
    End Property

    Public Property ButtonDropB As RibbonButton
        Get
            Return _ButtonDropB
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropB = value
        End Set
    End Property

    Public Property ButtonDropC As RibbonButton
        Get
            Return _ButtonDropC
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropC = value
        End Set
    End Property

    Public Sub New(ByVal ribbon As Ribbon)
        If ribbon Is Nothing Then Throw New ArgumentNullException(NameOf(ribbon), "Parameter is null")
        Me.Ribbon = ribbon
        Recents = New RibbonRecentItems(ribbon, Cmd.cmdRecents)
        ButtonNew = New RibbonButton(ribbon, Cmd.cmdButtonNew)
        ButtonOpen = New RibbonButton(ribbon, Cmd.cmdButtonOpen)
        ButtonSave = New RibbonButton(ribbon, Cmd.cmdButtonSave)
        RsharpDev = New RibbonDropDownButton(ribbon, Cmd.cmdRsharpDev)
        About = New RibbonButton(ribbon, Cmd.cmdAbout)
        Help = New RibbonHelpButton(ribbon, Cmd.cmdHelp)
        TabMain = New RibbonTab(ribbon, Cmd.cmdTabMain)
        GroupCommon = New RibbonGroup(ribbon, Cmd.cmdGroupCommon)
        GroupSimple = New RibbonGroup(ribbon, Cmd.cmdGroupSimple)
        ButtonSwitchToAdvanced = New RibbonButton(ribbon, Cmd.cmdButtonSwitchToAdvanced)
        RunScript = New RibbonButton(ribbon, Cmd.cmdRunScript)
        RunRemote = New RibbonButton(ribbon, Cmd.cmdRunRemote)
        GroupAdvanced = New RibbonGroup(ribbon, Cmd.cmdGroupAdvanced)
        ButtonSwitchToSimple = New RibbonButton(ribbon, Cmd.cmdButtonSwitchToSimple)
        ButtonDropA = New RibbonButton(ribbon, Cmd.cmdButtonDropA)
        ButtonDropB = New RibbonButton(ribbon, Cmd.cmdButtonDropB)
        ButtonDropC = New RibbonButton(ribbon, Cmd.cmdButtonDropC)
    End Sub
End Class
