// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdTabMain 1001 
#define cmdTabMain_LabelTitle_RESID 2
#define cmdGroupCommon 1002 
#define cmdGroupCommon_LabelTitle_RESID 3
#define cmdGroupSimple 1003 
#define cmdGroupSimple_LabelTitle_RESID 4
#define cmdGroupAdvanced 1004 
#define cmdGroupAdvanced_LabelTitle_RESID 5
#define cmdButtonNew 1005 
#define cmdButtonNew_LabelTitle_RESID 6
#define cmdButtonNew_LabelDescription_RESID 7
#define cmdButtonNew_TooltipTitle_RESID 8
#define cmdButtonNew_TooltipDescription_RESID 9
#define cmdButtonNew_SmallImages_RESID 10
#define cmdButtonNew_LargeImages_RESID 11
#define cmdButtonOpen 1006 
#define cmdButtonOpen_LabelTitle_RESID 12
#define cmdButtonOpen_LabelDescription_RESID 13
#define cmdButtonOpen_TooltipTitle_RESID 14
#define cmdButtonOpen_TooltipDescription_RESID 15
#define cmdButtonOpen_SmallImages_192__RESID 16
#define cmdButtonOpen_LargeImages_192__RESID 17
#define cmdButtonSave 1007 
#define cmdButtonSave_LabelTitle_RESID 18
#define cmdButtonSave_LabelDescription_RESID 19
#define cmdButtonSave_TooltipTitle_RESID 20
#define cmdButtonSave_TooltipDescription_RESID 21
#define cmdButtonSave_SmallImages_192__RESID 22
#define cmdButtonSave_LargeImages_192__RESID 23
#define cmdButtonDropA 1008 
#define cmdButtonDropA_LabelTitle_RESID 24
#define cmdButtonDropA_LabelDescription_RESID 25
#define cmdButtonDropA_TooltipTitle_RESID 26
#define cmdButtonDropB 1009 
#define cmdButtonDropB_LabelTitle_RESID 27
#define cmdButtonDropB_LabelDescription_RESID 28
#define cmdButtonDropB_TooltipTitle_RESID 29
#define cmdButtonDropC 1010 
#define cmdButtonDropC_LabelTitle_RESID 30
#define cmdButtonDropC_LabelDescription_RESID 31
#define cmdButtonDropC_TooltipTitle_RESID 32
#define cmdButtonSwitchToAdvanced 1011 
#define cmdButtonSwitchToAdvanced_LabelTitle_RESID 33
#define cmdButtonSwitchToAdvanced_LabelDescription_RESID 34
#define cmdButtonSwitchToAdvanced_TooltipTitle_RESID 35
#define cmdButtonSwitchToAdvanced_TooltipDescription_RESID 36
#define cmdButtonSwitchToSimple 1012 
#define cmdButtonSwitchToSimple_LabelTitle_RESID 37
#define cmdButtonSwitchToSimple_LabelDescription_RESID 38
#define cmdButtonSwitchToSimple_TooltipTitle_RESID 39
#define cmdButtonSwitchToSimple_TooltipDescription_RESID 40
#define cmdHelp 14 
#define cmdHelp_LabelTitle_RESID 41
#define cmdHelp_TooltipTitle_RESID 42
#define cmdHelp_SmallImages_192__RESID 43
#define cmdHelp_LargeImages_192__RESID 44
#define cmdRecents 15 
#define cmdRecents_LabelTitle_RESID 45
#define cmdAbout 16 
#define cmdAbout_LabelTitle_RESID 46
#define cmdAbout_SmallImages_192__RESID 47
#define cmdAbout_LargeImages_192__RESID 48
#define cmdRsharpDev 17 
#define cmdRsharpDev_LabelTitle_RESID 49
#define cmdRsharpDev_SmallImages_192__RESID 50
#define cmdRsharpDev_LargeImages_192__RESID 51
#define cmdRunScript 18 
#define cmdRunScript_LabelTitle_RESID 52
#define cmdRunScript_SmallImages_192__RESID 53
#define cmdRunScript_LargeImages_192__RESID 54
#define cmdRunRemote 19 
#define cmdRunRemote_LabelTitle_RESID 55
#define cmdRunRemote_SmallImages_192__RESID 56
#define cmdRunRemote_LargeImages_192__RESID 57
#define cmdSoluationTabGroup 20 
#define cmdSoluationTabGroup_LabelTitle_RESID 58
#define cmdViewProperty 21 
#define cmdViewProperty_LabelTitle_RESID 59
#define cmdSolutionTab 22 
#define cmdSolutionTab_LabelTitle_RESID 60
#define cmdConfigServer 23 
#define cmdConfigServer_LabelTitle_RESID 61
#define cmdConfigServer_LabelDescription_RESID 62
#define cmdConfigServer_SmallImages_192__RESID 63
#define cmdConfigServer_LargeImages_192__RESID 64
#define cmdClose 24 
#define cmdClose_LabelTitle_RESID 65
#define cmdClose_LabelDescription_RESID 66
#define cmdClose_TooltipTitle_RESID 67
#define cmdClose_TooltipDescription_RESID 68
#define cmdClose_SmallImages_192__RESID 69
#define cmdClose_LargeImages_192__RESID 70
#define cmdLicense 25 
#define cmdLicense_LabelTitle_RESID 60001
#define cmdLicense_LabelDescription_RESID 60002
#define cmdLicense_SmallImages_192__RESID 60003
#define cmdLicense_LargeImages_192__RESID 60004
#define cmdConfig 26 
#define cmdConfig_LabelTitle_RESID 60005
#define cmdConfig_LabelDescription_RESID 60006
#define cmdConfig_TooltipTitle_RESID 60007
#define cmdConfig_TooltipDescription_RESID 60008
#define cmdConfig_SmallImages_192__RESID 60009
#define cmdConfig_LargeImages_192__RESID 60010
#define cmdConsole 27 
#define cmdConsole_LabelTitle_RESID 60011
#define cmdConsole_LabelDescription_RESID 60012
#define cmdConsole_TooltipTitle_RESID 60013
#define cmdConsole_TooltipDescription_RESID 60014
#define cmdConsole_SmallImages_192__RESID 60015
#define cmdConsole_LargeImages_192__RESID 60016
#define InternalCmd2_LabelTitle_RESID 60017
#define InternalCmd6_LabelTitle_RESID 60018
#define InternalCmd8_LabelTitle_RESID 60019
