'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applets_screenshooter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applets_screenshooter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_x_object() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_x_object", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applications_system() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_system", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applications_utilities() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_utilities", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_back_color_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_back_color_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_Forward_color_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_Forward_color_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baobab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baobab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property build_Selection_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("build_Selection_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cheese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property class_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("class_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cloud_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cloud_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Contract_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contract_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_open_recent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_open_recent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_print_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_print_preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_undo_rtl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_undo_rtl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FileGroup_10135_32x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileGroup_10135_32x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_Closed_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_Closed_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_documents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_documents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_Open_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_Open_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_pictures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_pictures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_publicshare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_publicshare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gnome_window_manager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gnome_window_manager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gparted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gparted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graph_highPerformanceComputingChart_5170_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph_highPerformanceComputingChart_5170_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manifest_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manifest_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property module_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("module_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Office_Excel_Application_32xMD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Office_Excel_Application_32xMD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Partition_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Partition_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PencilAngled_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PencilAngled_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PencilAngled_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PencilAngled_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property plink() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("plink", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preferences_desktop_locale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences_desktop_locale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preferences_system_notifications() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences_system_notifications", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preferences_system_sharing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences_system_sharing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pscp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pscp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R_sharp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R_sharp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property script_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("script_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Alert_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Alert_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Alert_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Alert_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Complete_and_ok_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Complete_and_ok_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Complete_and_ok_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Complete_and_ok_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Critical_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Critical_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Security_Shields_Critical_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security_Shields_Critical_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_Local_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_Local_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_Remote_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_Remote_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotationRed_No_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotationRed_No_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotationRed_No_32xMD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotationRed_No_32xMD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Alert_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Alert_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Alert_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Alert_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Blocked_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Blocked_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Blocked_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Blocked_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Complete_and_ok_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Complete_and_ok_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Complete_and_ok_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Complete_and_ok_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Critical_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Critical_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Critical_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Critical_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Help_and_inconclusive_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Help_and_inconclusive_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Help_and_inconclusive_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Help_and_inconclusive_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Information_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Information_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Information_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Information_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Pause_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Pause_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Pause_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Pause_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Play_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Play_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Play_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Play_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Required_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Required_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Required_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Required_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Stop_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Stop_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Stop_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Stop_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Warning_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Warning_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Warning_32xLG_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Warning_32xLG_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAnnotations_Warning_32xLG_color1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAnnotations_Warning_32xLG_color1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property system_software_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system_software_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Terminal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terminal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tracker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tracker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_trash_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_trash_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property vs() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("vs", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WorkItem_32xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkItem_32xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property XMLFile_828_32x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XMLFile_828_32x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
